name: Main

on: [push, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 16
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            TCT-Engine/build/libs/*-all.jar
            TCT-Game/build/libs/*-all.jar
